# -------------------------- Dev ---------------------------------------

FROM node:22-bullseye AS dev

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/* \
    # NOTE: yarn > 1.22.19 breaks yarn-install invoked by yarn
    && npm install -g yarn@8.6.0 yarn@1.22.19 --force \
    && git config --global --add safe.directory /code

WORKDIR /code

# Build stage for web app
FROM dev AS web-app-serve-build

COPY ./package.json /code/

RUN yarn install

COPY . /code/

# NOTE: These are set directly in `vite.config.ts`
# We're using raw web-app-serve placeholder values here to treat them as dynamic values
# NOTE: Static env variables:
# These env variables are use during build
ENV VITE_FIREBASE_API_KEY=WEB_APP_SERVE_PLACEHOLDER_VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=WEB_APP_SERVE_PLACEHOLDER_VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_DATABASE_URL=WEB_APP_SERVE_PLACEHOLDER_VITE_FIREBASE_DATABASE_URL
ENV VITE_FIREBASE_PROJECT_ID=WEB_APP_SERVE_PLACEHOLDER_VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=WEB_APP_SERVE_PLACEHOLDER_VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=WEB_APP_SERVE_PLACEHOLDER_VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=WEB_APP_SERVE_PLACEHOLDER_VITE_FIREBASE_APP_ID
ENV VITE_FIREBASE_MEASUREMENT_ID=WEB_APP_SERVE_PLACEHOLDER_VITE_FIREBASE_MEASUREMENT_ID

ENV VITE_COMMUNITY_DASHBOARD_URL=WEB_APP_SERVE_PLACEHOLDER_VITE_COMMUNITY_DASHBOARD_URL
ENV VITE_BASE_URL=WEB_APP_SERVE_PLACEHOLDER_VITE_BASE_URL
ENV VITE_PRIVACY_POLICY_URL=WEB_APP_SERVE_PLACEHOLDER_VITE_PRIVACY_POLICY_URL
ENV VITE_IMPRINT_URL=WEB_APP_SERVE_PLACEHOLDER_VITE_IMPRINT_URL
ENV VITE_APP_LOGO=WEB_APP_SERVE_PLACEHOLDER_VITE_APP_LOGO
ENV VITE_PROJECTS_FALLBACK_IMAGE=WEB_APP_SERVE_PLACEHOLDER_VITE_PROJECTS_FALLBACK_IMAGE
ENV VITE_ALLOW_UNVERIFIED_USERS=WEB_APP_SERVE_PLACEHOLDER_VITE_ALLOW_UNVERIFIED_USERS

# Locales
ENV VITE_DEFAULT_LOCALE=WEB_APP_SERVE_PLACEHOLDER_VITE_DEFAULT_LOCALE
ENV VITE_FALLBACK_LOCALE=WEB_APP_SERVE_PLACEHOLDER_VITE_FALLBACK_LOCALE
ENV VITE_SUPPORTED_LOCALES=WEB_APP_SERVE_PLACEHOLDER_VITE_SUPPORTED_LOCALES

# Theme
ENV VITE_THEME_LIGHT_PRIMARY=WEB_APP_SERVE_PLACEHOLDER_VITE_THEME_LIGHT_PRIMARY
ENV VITE_THEME_LIGHT_SECONDARY=WEB_APP_SERVE_PLACEHOLDER_VITE_THEME_LIGHT_SECONDARY
ENV VITE_THEME_LIGHT_TERTIARY=WEB_APP_SERVE_PLACEHOLDER_VITE_THEME_LIGHT_TERTIARY
ENV VITE_THEME_LIGHT_ACCENT=WEB_APP_SERVE_PLACEHOLDER_VITE_THEME_LIGHT_ACCENT
ENV VITE_THEME_LIGHT_ERROR=WEB_APP_SERVE_PLACEHOLDER_VITE_THEME_LIGHT_ERROR
ENV VITE_THEME_LIGHT_WARNING=WEB_APP_SERVE_PLACEHOLDER_VITE_THEME_LIGHT_WARNING
ENV VITE_THEME_LIGHT_INFO=WEB_APP_SERVE_PLACEHOLDER_VITE_THEME_LIGHT_INFO
ENV VITE_THEME_LIGHT_SUCCESS=WEB_APP_SERVE_PLACEHOLDER_VITE_THEME_LIGHT_SUCCESS
ENV VITE_THEME_LIGHT_NEUTRAL=WEB_APP_SERVE_PLACEHOLDER_VITE_THEME_LIGHT_NEUTRAL

# App Attribution
ENV VITE_APP_NAME=WEB_APP_SERVE_PLACEHOLDER_VITE_APP_NAME
ENV VITE_APP_WEBSITE_URL=WEB_APP_SERVE_PLACEHOLDER_VITE_APP_WEBSITE_URL
ENV VITE_APP_ATTRIBUTION_TITLE=WEB_APP_SERVE_PLACEHOLDER_VITE_APP_ATTRIBUTION_TITLE
ENV VITE_APP_ATTRIBUTION_URL=WEB_APP_SERVE_PLACEHOLDER_VITE_APP_ATTRIBUTION_URL

ENV APPLY_CONFIG__ENABLE_DEBUG=false
ENV APPLY_CONFIG__DEBUG_USE_BIOME=true

ENV APPLY_CONFIG__DESTINATION_DIRECTORY=/usr/share/nginx/html/
ENV APPLY_CONFIG__APPLY_CONFIG_PATH=/web-app-serve/default-app-apply-config.sh

RUN WEB_APP_SERVE_ENABLED=true yarn build-only --outDir=/code/build

COPY ./src/ /web-app-serve/

FROM web-app-serve AS web-app-serve-example

LABEL maintainer="Togglecorp"
LABEL org.opencontainers.image.source="github.com/mapswipe/mapswipe-web"

FROM ghcr.io/toggle-corp/web-app-serve:v0.1.2 AS web-app-serve

# Env for apply-config script
ENV APPLY_CONFIG__SOURCE_DIRECTORY=/code/build/

COPY --from=web-app-serve-build /code/build "$APPLY_CONFIG__SOURCE_DIRECTORY"
